[phases.setup]
nixPkgs = ["python310", "postgresql_14", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "python3.10 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install apache-superset psycopg2-binary"
]

[start]
cmd = "bash start.sh"
